ToDo_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
]

todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:id>/delete/', views.delete, name='delete'),
    # path('todo/<str:category>/', views.todo_category, name='todo_category'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('category_list/', views.category_list, name='category_list'),
    path('user_data_input/', views.user_data_input, name='user_data_input'),
    path('user_data_confirm', views.user_data_confirm, name='user_data_confirm'),
    path('user_data_create', views.user_data_create, name='user_data_create'),
    # path('user_list', views.UserList.as_view(), name='user_list'),
    path('create_category_input', views.create_category_input, name='create_category_input'),
    path('create_category_confirm', views.create_category_confirm, name='create_category_confirm'),
    path('create_category_save', views.create_category_save, name='create_category_save'),
    # ToDoを作る
    path('create_todo_input', views.create_todo_input, name='create_todo_input'),
    path('create_todo_confirm', views.create_todo_confirm, name='create_todo_confirm'),
    path('create_todo_save', views.create_todo_save, name='create_todo_save'),
    path('todo_list/<int:pk>', views.todo_list, name='todo_list'),
]

todo_app/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
)
from django.contrib.auth import get_user_model
from django import forms
from .models import Category, ToDo

User = get_user_model()


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        def __init__(self, *args, **kwargs):
            super.__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title',)


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class ToDoForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        label='カテゴリー',
        queryset=Category.objects.all(),
    )

    class Meta:
        model = ToDo
        fields = ('title', 'category')


"""
    category = forms.ModelMultipleChoiceField(
        label="カテゴリー",
        queryset=Category.objects.all(),
        widget=forms.Select,)
"""

templates/todo/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>TODO</title>
        <link rel="stylesheet" href="{% static 'todo_app/ress.css' %}">
        <link rel="stylesheet" href="{% static 'todo_app/style.css' %}">
    </head>
    <body>
    <div class="header">
        <h2><a href="{% url 'todo:index' %}">ToDo App</a></h2>
        <ul>
                <li><a href="{% url 'todo:category_list' %}">カテゴリーから探す</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'todo:create_category_input' %}">カテゴリーを作成</a></li>
                <li><a href="{% url 'todo:create_todo_input' %}">ToDoを作成</a></li>
                <li><a href="{% url 'todo:logout' %}">ログアウト</a></li>
                {% else %}
                <li><a href="{% url 'todo:login' %}">ログイン</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
    </body>
</html>

templates/todo/category_list.html
{% extends "todo/base.html" %}
{% block content %}
    <div class="category_list_wrap">
    {% for category in category_list %}
        <ul class="category_list">
                <li><a href="{% url 'todo:todo_list' pk=category.pk %}">{{ category.title }}></a></li>
        </ul>
    {% endfor %}
    </div>
{% endblock %}

templates/todo/create.html
{% extends 'todo/base.html' %}

{% block content %}
    <form method="POST" action="{% url 'create_account' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password1 }}
      {{ form.password1.errors }}
      <label>パスワード(確認)</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <button type = "submit">登録</button>
    </form>
{% endblock %}

templates/todo/create_category_confirm.html
{% extends "todo/base.html" %}
{% block content %}
    {% for field in category_form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
    </div>
    {% endfor %}

    <a href="{% url 'todo:create_category_input' %}" class="btn btn-primary btn-lg">戻る</a>
    <hr>
    <form action="{% url 'todo:create_category_save' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% csrf_token %}
    </form>
{% endblock %}

templates/todo/create_category_input.html
{% extends 'todo/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ category_form.non_field_errors }}
        {% for field in category_form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        </form>
{% endblock %}

templates/todo/create_todo_confirm.html
{% extends "todo/base.html" %}
{% block content %}
    {% for field in form %}
        {% if field.id_for_label == 'id_title' %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
    </div>
        {% endif %}
    {% endfor %}
    <div class="form-group">
        <label for="id_category">カテゴリー: </label>
        {{ category_name }}
    </div>
    <a href="{% url 'todo:create_todo_input' %}" class="btn btn-primary btn-lg">戻る</a>
    <hr>
    <form action="{% url 'todo:create_todo_save' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% csrf_token %}
    </form>
{% endblock %}

templates/todo/create_todo_input.html
{% extends 'todo/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ todo_form.non_field_errors }}
        {% for field in todo_form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        </form>
{% endblock %}

templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
<div>
    <h2>TODOリスト</h2>

    {% if category %}
        <h2>カテゴリー: {{ category.title }}</h2>
    {% endif %}

    {% for todos in todo %}
        <ul>
            <li class="todo_title">{{ todos.title }}</li>
            <li class="todo_created_at">{{ todos.created_at }}</li>
        </ul>
    {% endfor %}
</div>
{% endblock %}

templates/todo/login.html
{% extends "todo/base.html" %}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
    <div>
        <a href="{% url 'todo:user_data_input' %}">新しいアカウントを作る</a>
    </div>
{% endblock %}

templates/todo/todo_list.html
{% extends "todo/base.html" %}
{% block content %}
    <div>
    {% if todos %}
    {% for todo in todos %}
        <ul class="todo_list">
            <li class="todo_title">{{ todo.title }}</li>
            <li class="todo_created_at">{{ todo.created_at }}</li>
        </ul>
    {% endfor %}
        {% else %}
        <h2>現在、このカテゴリーのToDoは存在しません</h2>
    {% endif %}
    </div>
{% endblock %}

templates/todo/user_data_confirm.html
{% extends "todo/base.html" %}
{% block content %}
    {% for field in form %}
        {% if field.id_for_label == 'id_username' or field.id_for_label == 'id_email' %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
    </div>
        {% endif %}
    {% endfor %}

    <a href="{% url 'todo:user_data_input' %}" class="btn btn-primary btn-lg">戻る</a>
    <hr>
    <form action="{% url 'todo:user_data_create' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% csrf_token %}
    </form>
{% endblock %}

templates/todo/user_data_input.html
{% extends "todo/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/todo/user_list.html
{% extends "todo/base.html" %}
{% block content %}
<p><a href="{% url 'todo:user_data_input' %}">ユーザー作成</a></p><hr>
{% for user in user_list %}
    <p>ユーザー名: {{ user.username }}</p><hr>
{% endfor %}
{% endblock %}